VeryCD=window.VeryCD||{};VeryCD.namespace=function(a){if(!a||!a.length)return null;a=a.split(".");for(var b=VeryCD,d=a[0]=="VeryCD"?1:0;d<a.length;d++){b[a[d]]=b[a[d]]||{};b=b[a[d]]}return b};VeryCD.namespace("config");VeryCD.namespace("events");VeryCD.namespace("client");VeryCD.namespace("cookie");VeryCD.namespace("layout");VeryCD.namespace("member");VeryCD.namespace("Members");VeryCD.namespace("util");VeryCD.DOM=document.compatMode&&document.compatMode=="CSS1Compat"?document.documentElement:document.body;
VeryCD.config.root={statics:"https:"==document.location.protocol?"https://ssl-v4.vcimg.com":"http://v4.vcimg.com",img:"http://img.verycd.com",doc:"http://doc.verycd.com",dynamic:"http://www.verycd.com",secure:"http://secure.verycd.com",yui:"http://cn.yui.yahooapis.com/2.5.2/build"};$=YAHOO.util.Dom.get;getElementsByClassName=YAHOO.util.Dom.getElementsByClassName;
VeryCD.cookie={get:function(a){for(var b=a+"=",d=b.length,e=document.cookie.length,f=0;f<e;){a=f+d;if(document.cookie.substring(f,a)==b){b=document.cookie.indexOf(";",a);if(b==-1)b=document.cookie.length;return decodeURIComponent(document.cookie.substring(a,b))}f=document.cookie.indexOf(" ",f)+1;if(f==0)break}return null},set:function(a,b){var d=arguments,e=arguments.length,f=e>2?d[2]:null,g=e>3?d[3]:null,h=e>4?d[4]:null;d=e>5?d[5]:false;document.cookie=a+"="+encodeURIComponent(b)+(f==null?"":"; expires="+
f.toGMTString())+(g==null?"":"; path="+g)+(h==null?"":"; domain="+h)+(d==true?"; secure":"")}};var getCookie=VeryCD.cookie.get,setCookie=VeryCD.cookie.set,readCookie=VeryCD.cookie.get;if(1!=getCookie("is_root"))window.onerror=function(){return false};VeryCD.client.agent={ie:false,ie5:false,ie6:false,ie7:false,opera:!!window.opera,webkit:navigator.userAgent.indexOf("AppleWebKit/")>-1,gecko:navigator.userAgent.indexOf("Gecko")>-1&&navigator.userAgent.indexOf("KHTML")==-1};document.write('<\!--[if IE]>  <script type="text/javascript">VeryCD.client.agent.ie  = true;<\/script><![endif]--\>');
document.write('<\!--[if IE 5]><script type="text/javascript">VeryCD.client.agent.ie5 = true;<\/script><![endif]--\>');document.write('<\!--[if IE 6]><script type="text/javascript">VeryCD.client.agent.ie6 = true;<\/script><![endif]--\>');document.write('<\!--[if IE 7]><script type="text/javascript">VeryCD.client.agent.ie7 = true;<\/script><![endif]--\>');VeryCD.userAgent=navigator.userAgent.toLowerCase();VeryCD.is_firefox=VeryCD.userAgent.indexOf("firefox")>=0?true:false;
VeryCD.is_safari=VeryCD.userAgent.indexOf("safari")>=0?true:false;VeryCD.is_chrome=VeryCD.userAgent.indexOf("chrome")>=0?true:false;if(VeryCD.is_chrome)VeryCD.is_safari=false;VeryCD.member.id=parseInt(VeryCD.cookie.get("member_id"));if(!VeryCD.member.id)VeryCD.member.id=0;VeryCD.member.mgroupId=parseInt(VeryCD.cookie.get("mgroupId"));if(!VeryCD.member.mgroupId)VeryCD.member.mgroupId=0;VeryCD.member.username=VeryCD.member.id==0?"":VeryCD.cookie.get("member_name");var locHostName="";
VeryCD.member.showUnreadMessage='<a href="http://home.verycd.com/space.php?do=pm" onclick="pageTracker._trackPageview(\'/stat/toplinkMsg/\')" target="_blank"><img alt="" src="'+VeryCD.config.root.statics+'/images/message/nomessage.gif" style="margin-bottom:0px;#margin-bottom:-4px" title="\u4f60\u67090\u6761\u65b0\u6d88\u606f"/></a>';if(VeryCD.member.id)if(location.hostname=="game.verycd.com"||location.hostname=="find.verycd.com")locHostName="http://www.verycd.com";
VeryCD.member.showUserName=function(){if(VeryCD.member.username!=""){if($("header_login"))$("header_login").innerHTML="<div style='padding-top:2px;'><b><a target='_blank' href='http://home.verycd.com/space.php?do=home' onclick=\"pageTracker._trackPageview('/stat/toplinkMembers/')\">"+VeryCD.member.username+"</a></b><span id='top_message_div'></span> <span id='top_sinat_div' style='position:relative;'></span> | <a target=\"_blank\" href=\"http://www.verycd.com/base/i/\" onclick=\"VeryCD.Track('/stat/toplinkMybase/')\">\u6211\u7684\u5927\u5168</a> | <a target='_blank' href='http://home.verycd.com/vc_my_iframe.php?myiframe=my_favorites' onclick=\"pageTracker._trackPageview('/stat/toplinkFav/')\">\u6536\u85cf</a> | <a href='http://secure.verycd.com/signout/*/"+
document.location.href+"' onclick=\"pageTracker._trackPageview('/stat/toplinkSignout/')\">\u9000\u51fa</a></div>";YAHOO.util.Get.script("http://www.verycd.com/ajax/member?m=messages&format=js",{onSuccess:function(){try{if(VeryCD.Members.Messages){VeryCD.member.unreadMessage=parseInt(VeryCD.Members.Messages.unRead);VeryCD.member.sinat=VeryCD.Members.Messages.sinat;if(!VeryCD.member.unreadMessage)VeryCD.member.unreadMessage=0;VeryCD.member.showUnreadMessage="&nbsp;<a target='_blank' style='text-decoration:none;background-color:#F4F4F4;' href='http://home.verycd.com/space.php?do=pm&amp;filter=newpm' onclick=\"pageTracker._trackPageview('/stat/toplinkMsg/')\"><img align='absmiddle' title='\u4f60\u6709"+
VeryCD.member.unreadMessage+"\u6761\u65b0\u6d88\u606f' alt='' src='http://v4.vcimg.com/images/message/"+(VeryCD.member.unreadMessage>0?"newmessage.gif":"nomessage.gif")+"' /></a>"+(VeryCD.member.unreadMessage>0?"<a target='_blank' href='http://home.verycd.com/space.php?do=pm&amp;filter=newpm' onclick=\"pageTracker._trackPageview('/stat/toplinkMsg/')\">("+VeryCD.member.unreadMessage+")</a>":"&nbsp;");if($("top_message_div"))$("top_message_div").innerHTML=VeryCD.member.showUnreadMessage;if($("top_sinat_div")){$("top_sinat_div").innerHTML=
'<a id="sina_t_link" href="http://t.sina.com.cn/"></a>';if(VeryCD.member.sinat||$("sina_t_link").offsetHeight==2||VeryCD.is_safari)$("top_sinat_div").innerHTML="<a target='_blank' style='text-decoration:none;background-color:#F4F4F4;' href='http://www.verycd.com/account/sinat/' onclick=\"pageTracker._trackPageview('/stat/toplinkSina/')\"><img align='absmiddle' alt='' style='margin-top:-5px' title='"+(VeryCD.member.sinat?"\u4f60\u5df2\u7ed1\u5b9a\u65b0\u6d6a\u5fae\u535a":"\u4f60\u8fd8\u672a\u7ed1\u5b9a\u65b0\u6d6a\u5fae\u535a")+
"' src='http://v4.vcimg.com/images/message/"+(VeryCD.member.sinat?"sina.logo.gif":"sina.logo.gray.gif")+"' />&nbsp;</a>";else $("top_sinat_div").innerHTML=""}}}catch(a){}},onFailure:function(){}})}else if($("user-loginfo"))$("user-loginfo").innerHTML='<a href="'+VeryCD.config.root.secure+"/signin/*/"+location.href+'">\u767b\u5f55</a> | <a href="'+VeryCD.config.root.secure+"/signup/*/"+location.href+'">\u6ce8\u518c</a>'};
VeryCD.member.getMemberAvatarUrl=function(a,b){a||(a="0");if(b!="big"&&b!="middle")b="small";a="_00000000"+a;a=a.substr(a.length-9);var d=a.substr(0,3),e=a.substr(3,2),f=a.substr(5,2);return"http://ucimg.vcimg.com/avatar/"+d+"/"+e+"/"+f+"/"+a.substr(a.length-2)+"_avatar_"+b+".jpg"};
VeryCD.member.showUserFace=function(){if(VeryCD.member.id!=0){var a=(new Date).getTime();$("userFace").innerHTML='<img alt="" src="'+VeryCD.member.getMemberAvatarUrl(VeryCD.member.id)+"?"+a+'" class="faceLeft loginUser" />'}else $("userFace").innerHTML='<img alt="" src="'+VeryCD.member.getMemberAvatarUrl(VeryCD.member.id)+'" class="faceLeft loginUser" />'};
VeryCD.member.showOrzUrl=function(){if(VeryCD.member.id!=0)$("orz-link").innerHTML="<a href='"+locHostName+"/orz/' onclick=\"pageTracker._trackPageview('/stat/toplinkOrz/')\">\u5019\u9009\u533a</a> | ";else $("orz-link").innerHTML=""};
VeryCD.layout.searchToggler={modules:{folders:"\u8d44\u6e90",files:"\u6587\u4ef6",entries:"\u8d44\u6599"},currentModule:"entries",displayingMenu:false,autoCompletor:function(){},_inited:false,_linkElement:null,_imageElement:null,_optionsElement:null,_init:function(){if(!this._inited){this._imageElement=$("current-search-module-img");this._linkElement=$("search-module-toggle-link");this._optionsElement=$("search-module-options");this._inited=true}},_generateList:function(){var a="",b;for(b in this.modules)if(b!=
"extend"){n=this.modules[b];a+='<li><a href="#" onmousedown="return VeryCD.layout.searchToggler.selectModule(\''+b+'\');"><img alt="" src="'+VeryCD.config.root.statics+"/images/layout/search-modules/"+b+'.png" style="width: 18px; height: 18px; filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src=\''+VeryCD.config.root.statics+"/images/layout/search-modules/"+b+".png', sizingMethod='crop');\" onload=\"this.onload=''; if(this.style.filter) { this.src='"+VeryCD.config.root.statics+"/images/0.gif'; this.width=18; this.height=18; }\" />"+
n+"</a></li>"}return a},init:function(a){this.currentModule=a;var b="";b+='<span id="search-module-toggle">';b+='<img id="current-search-module-img" alt="" src="'+VeryCD.config.root.statics+"/images/layout/search-modules/"+a+'.png" style="cursor:default;width: 18px; height: 18px; filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src=\''+VeryCD.config.root.statics+"/images/layout/search-modules/"+a+".png', sizingMethod='crop');\" onload=\"this.onload=''; if(this.style.filter) { this.src='"+
VeryCD.config.root.statics+"/images/0.gif'; this.width=18; this.height=18; }\" /></span>";document.write(b)},generate:function(){var a="",b=arguments[0]||this.currentModule,d=VeryCD.cookie.get("lsm");if(d!=null)for(var e in this.modules)if(e==d)b=d;if(arguments.length==2)a=arguments[1];d="";d+="<script type=\"text/javascript\">showTopAddOptions = function(obj){var top_add_options = $('top_add_options');if (!top_add_options) return false;if (top_add_options.style.display == 'none') {pageTracker._trackPageview('/stat/topAdd/'); obj.className = 'top_add_link_on'; top_add_options.style.display = 'block'; pageTracker._trackPageview('/stat/topAdd/');} else {top_add_options.style.display = 'none';obj.className = 'top_add_link'; }};<\/script>\n";
d+='<div class="package"><div class="" id="top_add">';d+='<a class="top_add_link" href="#" onclick="showTopAddOptions(this);return false">\u5206\u4eab</a>';d+='<div class="top_add_options png" id="top_add_options" style="display:none;">';d+='<a href="http://www.verycd.com/articles/add" onclick="pageTracker._trackPageview(\'/stat/topAddArticle/\');" class="top_add_article">\u6587\u7ae0</a>';d+='<a href="http://www.verycd.com/base/add" onclick="pageTracker._trackPageview(\'/stat/topAddEntry/\');" class="top_add_entry">\u8d44\u6599</a>';
d+='<a href="http://www.verycd.com/topics/post" onclick="pageTracker._trackPageview(\'/stat/topAddTopic/\'); VeryCD.events.topSearchBar.goPublish(); return false;" class="top_add_topic">\u8d44\u6e90</a>';d+="</div></div>";d+='<form method="get" onsubmit="return VeryCD.events.topSearchBar.findIt(this.kw.value);">\n';d+='<div id="top-search" class="auto-complete">\n';d+='<script type="text/javascript">VeryCD.layout.searchToggler.init("'+b+'");<\/script>\n';d+='<input type="text"  id="top-search-input" name="kw" value="'+
a+'" class="yui-ac-input" />';d+='<button type="submit" id="top-search-button"  class="top-search-button">\u641c\u7d22</button>';d+='<button type="button" id="top-search-advance" class="top-search-button" onclick="return VeryCD.events.topSearchBar.goAdvance();">\u9ad8\u7ea7\u641c\u7d22</button>';d+='<div id="top-search-ac-container"></div>';d+="</div><\!-- End #top-search --\>\n";d+="</form>";d+="</div>";document.write(d);this.autoCompletor=new function(){this.formatter=function(f,g){var h=f[0],j=
f[1];h.substr(0,g.length);h.substr(g.length);return["<div class='result-result'><div class='result-quantity'>",j," \u7ed3\u679c</div><span class='result-query'>",h,"</span></div>"].join("")};this.ds=new YAHOO.widget.DS_XHR("/suggest",["\n","\t"]);this.ds.scriptQueryParam="q";this.ds.scriptQueryAppend="m="+VeryCD.layout.searchToggler.currentModule+"&format=xhr";this.ds.responseType=YAHOO.widget.DS_XHR.TYPE_FLAT;this.ds.maxCacheEntries=0;this.ds.queryMatchSubset=true;this.ds.connTimeout=5E3;this.ac=
new YAHOO.widget.AutoComplete("top-search-input","top-search-ac-container",this.ds);this.ac.delimChar="";this.ac.formatResult=this.formatter;this.ac.queryMatchCase=false;this.ac.queryMatchContains=false;this.ac.typeAhead=false;this.ac.useIFrame=true;this.ac.useShadow=false;this.ac.queryDelay=0;this.ac.minQueryLength=1;this.ac.maxResultsDisplayed=10;this.ac.autoHighlight=false;this.ac.itemSelectEvent.subscribe(function(){VeryCD.events.topSearchBar.findIt($("top-search-input").value)})}},selectModule:function(){this._init();
if(arguments.length==0)this.displayingMenu?this.hideOptions():this.showOptions();else{var a=arguments[0];this.currentModule=a;this.hideOptions();this._imageElement.src=VeryCD.config.root.statics+"/images/layout/search-modules/"+a+"-selected.gif";$("search-module-options-list").innerHTML=this._generateList(a);VeryCD.cookie.set("lsm",a)}return false},hideOptions:function(){this._optionsElement.style.display="none";this.displayingMenu=false},showOptions:function(){this._optionsElement.style.display=
"";this.displayingMenu=true}};VeryCD.events.resizeWindow=function(){switch(VeryCD.layout.pageWidth){case "full":if(!VeryCD.client.agent.webkit)$("page-wrapper").style.width="94%";break;case "broad":$("page-wrapper").style.width="990px"}};window.onload=VeryCD.events.resizeWindow;window.onresize=VeryCD.events.resizeWindow;
VeryCD.events.topSearchBar={findIt:function(a){location.href=a.indexOf("+")==-1&&a.indexOf("#")==-1?"http://www.verycd.com/search/"+VeryCD.layout.searchToggler.currentModule+"/"+this.formatKeywords(a):"http://www.verycd.com/search/"+VeryCD.layout.searchToggler.currentModule+"?kw="+this.formatKeywords(a);return false},searchSite:function(a){location.href="http://search.verycd.com/site/"+encodeURIComponent(a).replace(/\+/g,"%2B").replace(/(%20)+/,"+")+"/";return false},goAdvance:function(){location.href=
"http://www.verycd.com/search#advanced";return false},goPublish:function(){location.href="http://"+location.hostname+"/topics/post?back="+location.href;return false},formatKeywords:function(a){return encodeURIComponent(a).replace(/\+/g,"%2B").replace(/(%20)+/g,"+")}};
VeryCD.events.copy=function(a){if(window.clipboardData)window.clipboardData.setData("Text",a);else{var b=null;if(arguments.length==2)if(typeof $(arguments[1])=="object")b=$(arguments[1]);if(!b){b=document.createElement("div");b.id="flash-copier";document.body.appendChild(b);b=$("flash-copier")}b.innerHTML='<embed src="'+VeryCD.config.root.statics+'/images/clipboard.swf" FlashVars="clipboard='+encodeURIComponent(a).replace(/\+/g,"%2B")+'" width="0" height="0" type="application/x-shockwave-flash"></embed>'}};
var displayBroadPage=VeryCD.client.broadScreen,currentUserId=VeryCD.member.id;function searchFolders(a){VeryCD.layout.searchToggler.currentModule="folders";return typeof a.q.value=="string"?VeryCD.events.topSearchBar.findIt(a.q.value):typeof a.kw.value=="string"?VeryCD.events.topSearchBar.findIt(a.kw.value):false}function searchSite(a){return VeryCD.events.topSearchBar.searchSite(a)}
function searchTopics(){VeryCD.layout.searchToggler.currentModule="topics";return VeryCD.events.topSearchBar.findIt(o.q.value)}function postAct(a,b){b||(b="./");var d=document.createElement("form");d.setAttribute("method","POST");d.setAttribute("action",b);var e=document.createElement("input");e.setAttribute("type","hidden");e.setAttribute("name","method");e.setAttribute("value",a);d.appendChild(e);document.body.appendChild(d);d.submit();return false}
function getWindowLength(a,b){a=(typeof a=="undefined"?"error":a).toLowerCase();if("width".indexOf(a)===0)a="Width";else if("height".indexOf(a)===0)a="Height";else alert("wrong parameter"+a);for(var d=["offset"+a,"scroll"+a,"client"+a,"inner"+a],e=document.body,f=document.documentElement,g=0,h=0,j="",k=0;k<d.length;k++){j=d[k];h=e[j]>f[j]?e[j]:f[j];b&&alert(j+":"+h);if(!(typeof h=="undefined"||h<g)){c_attr=j;g=h}}b&&alert(c_attr+":"+g);return g}
if(!VeryCD.client.agent.ie){document.write('<style type="text/css" media="all">\n');document.write('body, input, textarea, select, button, td { font-family: "Lucida Grande", Tahoma, Arial, sans-serif; }');document.write("</style>\n")}
function IsInstallSupMiniQQ(a){if(VeryCD.client.agent.ie)try{if((new ActiveXObject("TimwpDll.TimwpCheck")).GetVersion()<a){location.href="http://is.qq.com/up_alarm.shtml";return false}return true}catch(b){location.href="http://is.qq.com/up_alarm.shtml";return false}else alert("\u62b1\u6b49\uff0c\u7531\u4e8e\u817e\u8baf\u6bd4\u8f83\u50bb\uff0c\u8fd9\u4e2a\u529f\u80fd\u53ea\u80fd\u5728IE\u4e0b\u4f7f\u7528:(")}
function RealAddPortal(a,b){if(IsInstallSupMiniQQ(b)==true)location.href=a==17002?"Tencent://AddPortal/?Menu=Yes&Exe=QQ&PanelID="+a:"Tencent://AddPortal/?Menu=Yes&PanelID="+a}
VeryCD.events.fixPostImagesWidth=function(){var a=document.getElementsByName("post_img");try{for(i=0;i<a.length;i++){var b=a[i];if(b.width>600){n=b.width/600;b.width=600}if(b.height>2E3){n=b.height/2E3;b.width/=n;b.height=2E3}}window.setTimeout("VeryCD.events.fixPostImagesWidth()",1E3)}catch(d){window.setTimeout("VeryCD.events.fixPostImagesWidth()",1E3)}};
var JSTarget={init:function(a,b){if(document.getElementById&&document.createElement&&document.appendChild){for(var d=typeof a=="undefined"||a==null?"class":a,e=typeof b=="undefined"||b==null?"non-html":b,f=document.getElementsByTagName("a"),g=RegExp("(^|\\s)"+e+"(\\s|$)"),h=0;h<f.length;h++){e=f[h];if(d=="class"&&g.test(e.className)||g.test(e.getAttribute(d)))e.onclick=JSTarget.openWin}oWarning=null}},openWin:function(a){a=!a?window.event:a;if(!(a.shiftKey||a.altKey||a.ctrlKey||a.metaKey))if(a=window.open(this.getAttribute("href"),
"_blank")){a.focus&&a.focus();return false}return true},addEvent:function(a,b,d){if(a.addEventListener)a.addEventListener(b,d,false);else if(a.attachEvent){a["e"+b+d]=d;a[b+d]=function(){a["e"+b+d](window.event)};a.attachEvent("on"+b,a[b+d])}}};JSTarget.addEvent(window,"load",function(){JSTarget.init("rel","external")});function iserror(a){a=$(a);if(!a)return false;a.style.borderColor="#FF4500";a.style.borderStyle="solid";a.style.borderWidth="2px"}
TxtRsz={formEl:null,adEv:function(a,b,d){typeof document.addEventListener!="undefined"?a.addEventListener(b,d,false):a.attachEvent("on"+b,d)},rmEv:function(a,b,d){typeof document.removeEventListener!="undefined"?a.removeEventListener(b,d,false):a.detachEvent("on"+b,d)},init:function(){document.getElementsByTagName("input");document.getElementById("handle").style.cursor="s-resize";TxtRsz.adEv(document,"mousedown",TxtRsz.initResize)},initResize:function(a){var b=document.getElementById("contents");
if(typeof a=="undefined")a=window.event;if((a.target||a.srcElement).id=="handle"){TxtRsz.formEl=b;TxtRsz.formEl.startWidth=TxtRsz.formEl.clientWidth;TxtRsz.formEl.startHeight=TxtRsz.formEl.clientHeight;TxtRsz.formEl.startX=a.clientX;TxtRsz.formEl.startY=a.clientY;TxtRsz.adEv(document,"mousemove",TxtRsz.resize);TxtRsz.adEv(document,"mouseup",TxtRsz.stopResize)}},resize:function(a){if(typeof a=="undefined")a=window.event;if(TxtRsz.formEl.type.toLowerCase()=="textarea"){TxtRsz.formEl.style.height=TxtRsz.formEl.startHeight+
(a.clientY-TxtRsz.formEl.startY)+"px";return false}},stopResize:function(){TxtRsz.rmEv(document,"mousedown",TxtRsz.initResize);TxtRsz.rmEv(document,"mousemove",TxtRsz.resize);for(var a=document.getElementsByTagName("textarea"),b=0;b<a.length;b++)a[b].style.cursor="text";a=document.getElementsByTagName("input");for(b=0;b<a.length;b++)if(a[b].type=="text")a[b].style.cursor="text"}};
VeryCD.util.text={getChars:function(a){var b=0,d=0,e=0,f=0;if(a==null||a=="")return 0;f=a.length;for(b=0;b<f;b++){e=a.charCodeAt(b);d+=e<127?1:2}return d},getLength:function(a){return this.getChars(a)},subString:function(a,b,d){var e=0;c=0;rstr="";var f=a.length;e=this.getLength(a);if(b<0)b=e+b;if(d<1)d=e+d;for(e=0;e<f;e++){if(c>=b)break;var g=a.charCodeAt(e);c+=g<127?1:2}for(;e<f;e++){g=a.charCodeAt(e);c+=g<127?1:2;rstr+=a.charAt(e);if(c>=d)break}return rstr},briefTitle:function(){var a="",b=61,
d="...";switch(arguments.length){case 3:d=arguments[2];case 2:b=arguments[1];case 1:a=arguments[0];break;case 0:return}var e=a;if(this.getLength(a)>b){b=Math.floor(b/2);e=this.subString(a,0,b)+d+this.subString(a,0-(b-this.getLength(d)))}return e}};
function js_vc_imgurl_format(a,b,d,e){var f="",g="";if(f=a.match(/(\d+)\/([0-9a-z]{32}\d+)/i)){g="http://image-"+f[1]+".verycd.com";if(typeof d!="undefined"&&d!="")g+="/"+d;g+="/"+f[2];if(typeof b!="undefined"&&b!="")g+="("+b+")";g+=typeof e!="undefined"&&e!=""?"/"+e:typeof b!="undefined"&&b!=""?"/thumb.jpg":"/origin.jpg";return g}else return a}
function js_vc_truncate(a,b,d,e){if(sb_strlen(a)<=b)return a;else{var f="";if(d=="true"){f=sb_substr(a,0,b/2);if(typeof e!="undefined"&&e!="")f+=e;f+=sb_substr(a,-b/2)}else{f=sb_substr(a,0,b);if(typeof e!="undefined"&&e!="")f+=e}return f}}function getChars(a){var b=0,d=0,e=0,f=0;if(a==null||a=="")return 0;f=a.length;for(b=0;b<f;b++){e=a.charCodeAt(b);d+=e<127?1:2}return d}function sb_strlen(a){return getChars(a)}
function sb_substr(a,b,d){var e=0;c=0;rstr="";var f=a.length;e=sb_strlen(a);if(b<0)b=e+b;if(d<1)d=e+d;for(e=0;e<f;e++){if(c>=b)break;var g=a.charCodeAt(e);c+=g<127?1:2}for(;e<f;e++){g=a.charCodeAt(e);c+=g<127?1:2;rstr+=a.charAt(e);if(c>=d)break}return rstr}
VeryCD.emule=new function(){this.version=function(){return this.object().GetEmuleVersion()};this.object=function(){if(this._activeXobject)return this._activeXobject;try{this._activeXobject=new ActiveXObject("IE2EM.IE2EMUrlTaker")}catch(a){if(function(){try{var d=navigator.mimeTypes["application/verycd-scriptable-plugin"];if(d)if(d.enablePlugin)return true}catch(e){}return false}()){var b=document.createElement("embed");b.style.visibility="hidden";b.type="application/verycd-scriptable-plugin";b.width=
0;b.height=0;document.body.appendChild(b);this._activeXobject=b}else this._activeXobject={SendUrl:function(){return false},GetEmuleVersion:function(){return false}}}return this._activeXobject};this.installed=function(){return this.version()?"e"==this.version().substr(0,1)||"miniMule"==this.version().substr(0,8)?true:false:false};this.SendUrl=function(a,b,d){return this.object().SendUrl(a,b,d)}};
var BrowserDetect={init:function(){this.browser=this.searchString(this.dataBrowser)||"An unknown browser";this.version=this.searchVersion(navigator.userAgent)||this.searchVersion(navigator.appVersion)||"an unknown version";this.OS=this.searchString(this.dataOS)||"an unknown OS"},searchString:function(a){for(var b=0;b<a.length;b++){var d=a[b].string,e=a[b].prop;this.versionSearchString=a[b].versionSearch||a[b].identity;if(d){if(d.indexOf(a[b].subString)!=-1)return a[b].identity}else if(e)return a[b].identity}},
searchVersion:function(a){var b=a.indexOf(this.versionSearchString);if(b!=-1)return parseFloat(a.substring(b+this.versionSearchString.length+1))},dataBrowser:[{string:navigator.userAgent,subString:"Chrome",identity:"Chrome"},{string:navigator.vendor,subString:"Apple",identity:"Safari",versionSearch:"Version"},{string:navigator.userAgent,subString:"Firefox",identity:"Firefox"},{string:navigator.userAgent,subString:"MSIE",identity:"Explorer",versionSearch:"MSIE"}],dataOS:[{string:navigator.platform,
subString:"Win",identity:"Windows"},{string:navigator.platform,subString:"Mac",identity:"Mac"},{string:navigator.platform,subString:"Linux",identity:"Linux"}]};BrowserDetect.init();
VeryCD.gotop={_gotop:null,ini:function(){var a=document.createElement("A");a.style.display="none";a.id="gotop";a.href="#";a.setAttribute("title","\u8fd4\u56de\u9876\u90e8");a.setAttribute("onFocus","this.blur()");a.innerHTML=' <span><em class="tr">\u2666</em><em class="tube">\u2590</em></span>';a.onclick=function(){pageTracker._trackPageview("/stat/gotop/");VeryCD.gotop.go();return false};document.body.appendChild(a);VeryCD.gotop._gotop=$("gotop");VeryCD.gotop._addScrollEven()},_addScrollEven:function(){VeryCD.client.agent.ie?
window.attachEvent("onscroll",VeryCD.gotop._scrollFn):window.addEventListener("scroll",VeryCD.gotop._scrollFn,false)},_scrollFn:function(){(VeryCD.DOM.scrollTop||document.body.scrollTop)<VeryCD.DOM.clientHeight?VeryCD.gotop._hide():VeryCD.gotop._show()},_show:function(){VeryCD.gotop._gotop.style.display="block"},_hide:function(){VeryCD.gotop._gotop.style.display="none"},go:function(){if(VeryCD.DOM.scrollTop)VeryCD.DOM.scrollTop=0;else document.body.scrollTop=0;return false}};
